### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by dimqua** [airstep/tubik#1]
Please consider to add the app to F-Droid, since it's open source.

**Comment by Rudloff** [comment]
Hello,
There is a ticket for this here: https://gitlab.com/fdroid/rfp/issues/365

**Comment by Poussinou** [comment]
Could you please also tag your releases (see [here](https://help.github.com/articles/creating-releases/)), it would be helpful for the F-Droid release. You could also attach the binaries to your releases (see [here](https://blog.github.com/2013-07-02-release-your-software/)).
